import { DateTime } from "luxon";
import { Categories } from "../enums/category.enum";
import { PaymentMethods } from "../enums/payment-method.enum";
import { Transaction } from "../types/transaction.type";

export const transactions: Transaction[] = [
  {
    source: "PriceSmart",
    value: -900000,
    date: DateTime.fromISO("2022-05-11"),
    paymentMethod: PaymentMethods.CREDIT,
    category: Categories.GROCERIES,
    details: [],
  },
  {
    source: "D1 - Cabanias",
    value: -40000,
    date: DateTime.fromISO("2022-05-11"),
    paymentMethod: PaymentMethods.CREDIT,
    category: Categories.FOOD,
    details: [],
  },
  {
    source: "Tienda Las Cabanias",
    value: -14000,
    date: DateTime.fromISO("2022-04-11"),
    paymentMethod: PaymentMethods.CASH,
    category: Categories.HOUSE,
    details: [],
  },
  {
    source: "Tienda Las Cabanias",
    value: -14000,
    date: DateTime.fromISO("2022-04-11"),
    paymentMethod: PaymentMethods.CASH,
    category: Categories.HOUSE,
    details: [],
  },
  {
    source: "Tienda Las Cabanias",
    value: -14000,
    date: DateTime.fromISO("2022-04-11"),
    paymentMethod: PaymentMethods.CASH,
    category: Categories.HOUSE,
    details: [],
  },
  {
    source: "Tienda Las Cabanias",
    value: -14000,
    date: DateTime.fromISO("2022-04-11"),
    paymentMethod: PaymentMethods.CASH,
    category: Categories.HOUSE,
    details: [],
  },
  {
    source: "Tienda Las Cabanias",
    value: -14000,
    date: DateTime.fromISO("2022-03-11"),
    paymentMethod: PaymentMethods.CASH,
    category: Categories.HOUSE,
    details: [],
  },
  {
    source: "Tienda Las Cabanias",
    value: -14000,
    date: DateTime.fromISO("2022-03-11"),
    paymentMethod: PaymentMethods.CASH,
    category: Categories.HOUSE,
    details: [],
  },
  {
    source: "Tienda Las Cabanias",
    value: -14000,
    date: DateTime.fromISO("2022-03-11"),
    paymentMethod: PaymentMethods.CASH,
    category: Categories.HOUSE,
    details: [],
  },
  {
    source: "Tienda Las Cabanias",
    value: -14000,
    date: DateTime.fromISO("2022-03-11"),
    paymentMethod: PaymentMethods.CASH,
    category: Categories.HOUSE,
    details: [],
  },
  {
    source: "Tienda Las Cabanias",
    value: -14000,
    date: DateTime.fromISO("2022-03-11"),
    paymentMethod: PaymentMethods.CASH,
    category: Categories.HOUSE,
    details: [],
  },
];
